Rerun autoconf and autoheader.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -681,6 +681,8 @@ MOWGLI_CFLAGS
 MOWGLI_LIBS
 subdirs
 LIBMOWGLI
+PCRE_CFLAGS
+PCRE_LIBS
 BUILDROOT
 LIBOBJS
 LTLIBOBJS'
@@ -1287,6 +1289,7 @@ Optional Packages:
   --without-libiconv-prefix     don't search for libiconv in includedir and libdir
   --with-libintl-prefix[=DIR]  search for libintl in DIR/include and DIR/lib
   --without-libintl-prefix     don't search for libintl in includedir and libdir
+  --with-pcre             Enable PCRE regular expression support
 
 Some influential environment variables:
   CC          C compiler command
@@ -10373,6 +10376,131 @@ LIBS="$LIBS $MOWGLI_LIBS"
 
 
 
+
+# Check whether --with-pcre was given.
+if test "${with_pcre+set}" = set; then
+  withval=$with_pcre;
+else
+  with_pcre=no
+fi
+
+
+if test "x$with_pcre" != xno; then
+
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        { echo "$as_me:$LINENO: checking for libpcre" >&5
+echo $ECHO_N "checking for libpcre... $ECHO_C" >&6; }
+
+        if $PKG_CONFIG --exists "libpcre" ; then
+            { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+            succeeded=yes
+
+            { echo "$as_me:$LINENO: checking PCRE_CFLAGS" >&5
+echo $ECHO_N "checking PCRE_CFLAGS... $ECHO_C" >&6; }
+            PCRE_CFLAGS=`$PKG_CONFIG --cflags "libpcre"`
+            { echo "$as_me:$LINENO: result: $PCRE_CFLAGS" >&5
+echo "${ECHO_T}$PCRE_CFLAGS" >&6; }
+
+            { echo "$as_me:$LINENO: checking PCRE_LIBS" >&5
+echo $ECHO_N "checking PCRE_LIBS... $ECHO_C" >&6; }
+            PCRE_LIBS=`$PKG_CONFIG --libs "libpcre"`
+            { echo "$as_me:$LINENO: result: $PCRE_LIBS" >&5
+echo "${ECHO_T}$PCRE_LIBS" >&6; }
+        else
+	    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+            PCRE_CFLAGS=""
+            PCRE_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            PCRE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libpcre"`
+
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+     :
+  else
+
+		{ { echo "$as_me:$LINENO: error: PCRE requested, but not found." >&5
+echo "$as_me: error: PCRE requested, but not found." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+	CFLAGS="$CFLAGS $PCRE_CFLAGS"
+	LIBS="$LIBS $PCRE_LIBS"
+
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PCRE 1
+_ACEOF
+
+fi
+
 BUILDROOT=`pwd`
 
 
@@ -11171,12 +11299,14 @@ for ac_last_try in false false false false false :; do
 MOWGLI_LIBS!$MOWGLI_LIBS$ac_delim
 subdirs!$subdirs$ac_delim
 LIBMOWGLI!$LIBMOWGLI$ac_delim
+PCRE_CFLAGS!$PCRE_CFLAGS$ac_delim
+PCRE_LIBS!$PCRE_LIBS$ac_delim
 BUILDROOT!$BUILDROOT$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 6; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 8; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -11909,6 +12039,7 @@ Configuration:
 	Socket Engine        : ${SOCKET_ENGINE}
 	Block Allocator      : ${balloc}
 	Mowgli installation  : ${MOWGLI_SOURCE}
+	PCRE support         : ${with_pcre}
 	CFLAGS               : ${CFLAGS}
 
 Type make to build Atheme, and make install to install it."
